name: Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-home-cache-cleanup: true

    - name: Build with Gradle
      run: |
        # Try to use the Gradle wrapper if it exists
        if [ -f "./gradlew" ]; then
          chmod +x gradlew
          ./gradlew assembleDebug
        else
          # Fall back to using Gradle directly
          gradle assembleDebug
        fi
      env:
        ORG_GRADLE_PROJECT_keystoreProperties: ${{ secrets.KEYSTORE_PROPERTIES }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 7

    # Optional: Uncomment to upload to GitHub Releases when a tag is pushed
    # - name: Upload Release Assets
    #   if: startsWith(github.ref, 'refs/tags/')
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     files: app/build/outputs/apk/debug/app-debug.apk
    #     fail_orphans: true
